{
 "title": "Kin Statistics",
 "description": "Growth of the Kin ecosystem based on users and transactions",
 "time": { "from": "2018-06-25T00:00:00.000Z", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total Users",
   "type": "singlestat",
   "description": "Total number of accounts on the Kin blockchain",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n        SUM(`create_account`.`quantity`) AS `quantity`\n    FROM\n        `create_account`"
    }
   ]
  },
  {
   "title": "New users",
   "type": "singlestat",
   "description": "New users on the Kin blockchain",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(TIMESTAMP(\n                 MAKEDATE(year, day),\n                 SEC_TO_TIME(1 * 24 * 60 * 60))) as time,\n\n SUM(quantity) as new_users FROM kin.create_account GROUP BY day, year"
    }
   ]
  },
  {
   "title": "Active users 24 hours",
   "type": "singlestat",
   "description": "Total number of daily active accounts on the Kin blockchain. As a reference - STEEM has 60,000 daily active users. Filling this bar means Kin's activity has matched STEEMs\n\n\nAn active account has either made or received a transaction. (provided or payed for a service - both are active)",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n        COUNT(`user_activity`.`account_id`) AS `quantity`\n    FROM\n        `user_activity` WHERE last_active >= DATE_SUB(NOW(), INTERVAL 1 DAY)"
    }
   ]
  },
  {
   "title": "KIN/ USD",
   "type": "singlestat",
   "description": "Price in USD per KIN according to coinmarketcap. Updated each minute",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 8 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ROUND(data,5) FROM \n       kin.key_value WHERE id = 'KIN_price'"
    }
   ]
  },
  {
   "title": "Metcalf projections - Daily Active Users to Price",
   "type": "graph",
   "description": "NV = k . n . log(n)\n\nNV = value (price)\nk = proportionality constant\nn = number of nodes\n\nNote 1: k is calculated dynamically from two data points.\n\nNote 2: this is not a price predictor, but simply an experiment to see how closely Kin follows Metacalf's law",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Price" }
   ],
   "targets": [
    {
     "rawSql": "SELECT now() as time,  CONVERT(FORMAT(daily_active_users,0), CHAR) as metric, price as 'projected price' from metacalf WHERE n > 1"
    }
   ]
  },
  {
   "title": "KIN/ BTC marketcap",
   "type": "singlestat",
   "description": "Approaches 1 as Kin marketcap rises",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ((SELECT data FROM kin.key_value WHERE id = 'KIN_marketcap')/\n(SELECT data FROM kin.key_value WHERE id = 'BTC_marketcap')) as flip\n       "
    }
   ]
  },
  {
   "title": "Marketcap Rank",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ROUND(data,0) as score FROM kin.key_value WHERE id = 'KIN_marketcap_rank' \n       "
    }
   ]
  },
  {
   "title": "Alexa Rank",
   "type": "singlestat",
   "description": "The traffic rank is based on three months of aggregated historical traffic data from millions of Alexa Toolbar users and data obtained from other, diverse traffic data sources, and is a combined measure of page views and users (reach)",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ROUND(data,0) as score FROM kin.key_value WHERE id = 'KIN_alexa_score' \n       "
    }
   ]
  },
  {
   "title": "Reddit Subscribers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ROUND(data,0) as score FROM kin.key_value WHERE id = 'KIN_reddit_subscribers' \n       "
    }
   ]
  },
  {
   "title": "Twitter Followers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ROUND(data,0) as score FROM kin.key_value WHERE id = 'KIN_twitter_followers' \n       "
    }
   ]
  },
  {
   "title": "Community Score",
   "type": "singlestat",
   "description": "Cryptocurrencies tend to experience tremendous growth when there is a strong community backing it. \nA strong community contributes to new ideas and new features to be incorporated into the coin, \nincreases trading volume, and signifies growth towards a bigger market. (eg. Reddit, Facebook, etc.)",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ROUND(data,1) as score FROM kin.key_value WHERE id = 'KIN_community_score' \n       "
    }
   ]
  },
  {
   "title": "Public Interest Score",
   "type": "singlestat",
   "description": "Search engine total results and web popularity can be used to measure mainstream interest and popularity of a coin.",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 16 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT ROUND(data,0) as score FROM kin.key_value WHERE id = 'KIN_public_interest_score' \n       "
    }
   ]
  },
  {
   "title": "Hourly active users",
   "type": "graph",
   "description": "Hourly active users",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT  time_period as time,\nquantity as active_users FROM kin.hourly_active_users"
    }
   ]
  },
  {
   "title": "Accounts created per minute",
   "type": "graph",
   "description": "Accounts created per minute",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(TIMESTAMP(MAKEDATE(year, day),SEC_TO_TIME(hour * 60 * 60))) as time, \nquantity/60 as accounts_created_per_minute \nFROM kin.create_account"
    }
   ]
  },
  {
   "title": "New users created",
   "type": "graph",
   "description": "New users created per hour",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(TIMESTAMP(MAKEDATE(year, day),SEC_TO_TIME(hour * 60 * 60))) as time, quantity as new_user FROM kin.create_account"
    }
   ]
  },
  {
   "title": "Total users",
   "type": "graph",
   "description": "Total user accounts created",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT UNIX_TIMESTAMP(TIMESTAMP(MAKEDATE(year, day),SEC_TO_TIME(hour * 60 * 60))) as time, cumulative_quantity as total_users FROM kin.create_account"
    }
   ]
  },
  {
   "title": "Number of Earn/Spend transactions",
   "type": "graph",
   "description": "Number of transactions per hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(TIMESTAMP(\n                 MAKEDATE(year, day),\n                 SEC_TO_TIME(hour * 60 * 60))) as time,\n\nquantity as transactions FROM kin.payment"
    }
   ]
  },
  {
   "title": "Total Earn/Spend transactions",
   "type": "graph",
   "description": "Total Earn/Spend transactions",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(TIMESTAMP(\n                 MAKEDATE(year, day),\n                 SEC_TO_TIME(hour * 60 * 60))) as time,\n\ncumulative_quantity as total_transactions FROM kin.payment"
    }
   ]
  },
  {
   "title": "Volume of Earn/Spend transactions",
   "type": "graph",
   "description": "Total daily volume of Kin transacted by users per hour",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(TIMESTAMP(\n                 MAKEDATE(year, day),\n                 SEC_TO_TIME(hour * 60 * 60))) as time,\n\nvolume as volume FROM kin.payment"
    }
   ]
  },
  {
   "title": "Earn/ Spend transactions per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(TIMESTAMP(\n                 MAKEDATE(year, day),\n                 SEC_TO_TIME(hour * 60 * 60))) as time,\n\n quantity/86400 as tps FROM kin.payment"
    }
   ]
  },
  {
   "title": "Average transactions per user",
   "type": "graph",
   "description": "Total transactions divided by total users to date",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(TIMESTAMP(\n                 MAKEDATE(p.year, p.day),\n                 CONCAT(p.hour,\":00:00\"))) as time,\n\n (p.cumulative_quantity)/(SELECT (ca.cumulative_quantity) FROM create_account ca WHERE ca.year = p.year AND ca.day = p.day AND ca.hour = p.hour) as atpu FROM kin.payment p "
    }
   ]
  }
 ]
}