{
 "title": "KIN Evolution stats",
 "description": "Growth of the Kin ecosystem based on users and transactions",
 "time": { "from": "2018-06-25T00:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Total Users",
   "type": "singlestat",
   "description": "Total number of accounts on the Kin blockchain",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT \n        SUM(`create_account`.`quantity`) AS `quantity`\n    FROM\n        `create_account`"
    }
   ]
  },
  {
   "title": "Earn/ Spend transactions",
   "type": "graph",
   "description": "Number of transactions per day",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(TIMESTAMP(\n                 MAKEDATE(year, day),\n                 SEC_TO_TIME(1 * 24 * 60 * 60))) as time,\n\n SUM(quantity) as transactions FROM kin.payment GROUP BY day, year"
    }
   ]
  },
  {
   "title": "New users",
   "type": "singlestat",
   "description": "New users on the Kin blockchain",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 9 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(TIMESTAMP(\n                 MAKEDATE(year, day),\n                 SEC_TO_TIME(1 * 24 * 60 * 60))) as time,\n\n SUM(quantity) as new_users FROM kin.create_account GROUP BY day, year"
    }
   ]
  },
  {
   "title": "Earn/ Spend volume",
   "type": "graph",
   "description": "Total daily volume of Kin transacted by users",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\nUNIX_TIMESTAMP(TIMESTAMP(\n                 MAKEDATE(year, day),\n                 SEC_TO_TIME(1 * 24 * 60 * 60))) as time,\n\n SUM(volume) as volume FROM kin.payment GROUP BY day, year"
    }
   ]
  }
 ]
}